### ISSUE TITLE
Docker compose up doesn't run any server anymore?

### ISSUE THREAD

**Issue by onekiloparsec** [ASCOMInitiative/ASCOM.Alpaca.Simulators#38]
Hi. As rapidly mentionned in my MR #37, I'am having troubles running the simulators with the Docker compose command. Hence, I investigated a bit with `git bisect`. 

The missing `COPY` commands in the Dockerfile starts with commit c9f61669, but that's easy to fix. Hence, with a git bisect, I was able to identify at which commit, the `docker compuse up --build` command doesn't start the server anymore. 

The "faulty" commit is b9cf9c6b (i.e. the one right after the one mentionned above). This looks like an important refactoring indeed.

I am sorry, I really don't know the .NET ecosystem, and I am unable to suggest a PR. Could you have a look? 

When I make a `git checkout` to that problematic commit, and I add the missine `COPY` line in the Docker file (`COPY OmniSim.BaseDriver/*.csproj ./OmniSim.BaseDriver/`), and I run the `docker compose` command, this is the log I get (note the final `exit 0`):

```
✘ onekiloparsec@hal9014  ~/code/ASCOM.Alpaca.Simulators  ➦ b9cf9c6 ● <B> docker compose up --build
WARN[0000] /Users/onekiloparsec/code/ASCOM.Alpaca.Simulators/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Building 8.7s (40/40) FINISHED                                                                                                                                                                   docker:desktop-linux
 => [web internal] load build definition from Dockerfile                                                                                                                                                             0.0s
 => => transferring dockerfile: 1.66kB                                                                                                                                                                               0.0s
 => [web] resolve image config for docker-image://docker.io/docker/dockerfile:1                                                                                                                                      1.0s
 => CACHED [web] docker-image://docker.io/docker/dockerfile:1@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb                                                                                0.0s
 => => resolve docker.io/docker/dockerfile:1@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb                                                                                                 0.0s
 => [web internal] load build definition from Dockerfile                                                                                                                                                             0.0s
 => [web internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0                                                                                                                                                0.2s
 => [web internal] load metadata for mcr.microsoft.com/dotnet/aspnet:8.0                                                                                                                                             0.2s
 => [web internal] load .dockerignore                                                                                                                                                                                0.0s
 => => transferring context: 4.77kB                                                                                                                                                                                  0.0s
 => [web build  1/27] FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:2d7f935b8c7fe032cd3d36b5ce9c82c24413881e6dad1b4fbdf36cf369e4244f                                                                                  0.0s
 => => resolve mcr.microsoft.com/dotnet/sdk:8.0@sha256:2d7f935b8c7fe032cd3d36b5ce9c82c24413881e6dad1b4fbdf36cf369e4244f                                                                                              0.0s
 => [web runtime 1/3] FROM mcr.microsoft.com/dotnet/aspnet:8.0@sha256:3a305bc84767bbb651bd035119fe319a91fe927155706f7296499ca0205c812a                                                                               0.0s
 => => resolve mcr.microsoft.com/dotnet/aspnet:8.0@sha256:3a305bc84767bbb651bd035119fe319a91fe927155706f7296499ca0205c812a                                                                                           0.0s
 => [web internal] load build context                                                                                                                                                                                0.0s
 => => transferring context: 40.25kB                                                                                                                                                                                 0.0s
 => CACHED [web build  2/27] WORKDIR /app                                                                                                                                                                            0.0s
 => CACHED [web build  3/27] COPY NuGet.config .                                                                                                                                                                     0.0s
 => CACHED [web build  4/27] COPY license.md .                                                                                                                                                                       0.0s
 => CACHED [web build  5/27] COPY *.sln .                                                                                                                                                                            0.0s
 => CACHED [web build  6/27] COPY ASCOM.Alpaca.Simulators/*.csproj ./ASCOM.Alpaca.Simulators/                                                                                                                        0.0s
 => CACHED [web build  7/27] COPY ASCOM.Alpaca.Razor/*.csproj ./ASCOM.Alpaca.Razor/                                                                                                                                  0.0s
 => CACHED [web build  8/27] COPY ASCOM.COM.LocalServer/*.csproj ./ASCOM.COM.LocalServer/                                                                                                                            0.0s
 => CACHED [web build  9/27] COPY Camera.Simulator/*.csproj ./Camera.Simulator/                                                                                                                                      0.0s
 => CACHED [web build 10/27] COPY CoverCalibratorSimulator/*.csproj ./CoverCalibratorSimulator/                                                                                                                      0.0s
 => CACHED [web build 11/27] COPY DomeSimulator/*.csproj ./DomeSimulator/                                                                                                                                            0.0s
 => CACHED [web build 12/27] COPY FilterWheelSimulator/*.csproj ./FilterWheelSimulator/                                                                                                                              0.0s
 => CACHED [web build 13/27] COPY FocuserSimulator/*.csproj ./FocuserSimulator/                                                                                                                                      0.0s
 => CACHED [web build 14/27] COPY ObservingConditionsSimulator/*.csproj ./ObservingConditionsSimulator/                                                                                                              0.0s
 => CACHED [web build 15/27] COPY OmniSim.BaseDriver/*.csproj ./OmniSim.BaseDriver/                                                                                                                                  0.0s
 => CACHED [web build 16/27] COPY OmniSim.Tools/*.csproj ./OmniSim.Tools/                                                                                                                                            0.0s
 => CACHED [web build 17/27] COPY RotatorSimulator/*.csproj ./RotatorSimulator/                                                                                                                                      0.0s
 => CACHED [web build 18/27] COPY SafetyMonitorSimulator/*.csproj ./SafetyMonitorSimulator/                                                                                                                          0.0s
 => CACHED [web build 19/27] COPY SwitchSimulator/*.csproj ./SwitchSimulator/                                                                                                                                        0.0s
 => CACHED [web build 20/27] COPY TelescopeSimulator/*.csproj ./TelescopeSimulator/                                                                                                                                  0.0s
 => CACHED [web build 21/27] COPY OmniSimCOMProxy/*.csproj ./OmniSimCOMProxy/                                                                                                                                        0.0s
 => CACHED [web build 22/27] COPY WindowsBase.Vector/*.sln ./WindowsBase.Vector/                                                                                                                                     0.0s
 => CACHED [web build 23/27] COPY WindowsBase.Vector/WindowsBase.Vector/*.csproj ./WindowsBase.Vector/WindowsBase.Vector/                                                                                            0.0s
 => CACHED [web build 24/27] RUN dotnet restore                                                                                                                                                                      0.0s
 => [web build 25/27] COPY . .                                                                                                                                                                                       0.1s
 => [web build 26/27] WORKDIR /app/ASCOM.Alpaca.Simulators                                                                                                                                                           0.0s
 => [web build 27/27] RUN dotnet publish -c Release -o out                                                                                                                                                           7.2s
 => CACHED [web runtime 2/3] WORKDIR /app                                                                                                                                                                            0.0s 
 => CACHED [web runtime 3/3] COPY --from=build /app/ASCOM.Alpaca.Simulators/out ./                                                                                                                                   0.0s 
 => [web] exporting to image                                                                                                                                                                                         0.0s 
 => => exporting layers                                                                                                                                                                                              0.0s 
 => => exporting manifest sha256:61e5c2a3e15ac10ad398edb90b1fe1f43ca0198272666f64d56d8748c4d3513c                                                                                                                    0.0s 
 => => exporting config sha256:ea246770fe6e9713885417a03cdbb8a15085679fe250998f9a69daec96aabf40                                                                                                                      0.0s 
 => => exporting attestation manifest sha256:8834caf74d20d4d081b3cfb94fc2110896daa6272657719ae635442956580d54                                                                                                        0.0s
 => => exporting manifest list sha256:a404d1bfee2128cdc2af5427af13c017b5a9e646dadfdf81aab9da7b7e46bd63                                                                                                               0.0s
 => => naming to docker.io/library/ascomalpacasimulators-web:latest                                                                                                                                                  0.0s
 => => unpacking to docker.io/library/ascomalpacasimulators-web:latest                                                                                                                                               0.0s
 => [web] resolving provenance for metadata file                                                                                                                                                                     0.0s
[+] Running 1/1
 ✔ Container ascomalpacasimulators-web-1  Recreated                                                                                                                                                                  0.1s 
Attaching to web-1
web-1  | ASCOM Alpaca Simulators version 0.4.1-rc.1
web-1  | 03/25/2025 13:03:11 [Information] - ASCOM Alpaca Simulators version 0.4.1-rc.1
web-1  | Running on: Debian GNU/Linux 12 (bookworm).
web-1  | 03/25/2025 13:03:11 [Information] - Running on: Debian GNU/Linux 12 (bookworm).
web-1  | 03/25/2025 13:03:11 [Information] - Camera 0 - UUID of bd2b8bef-cf86-44b2-b237-07608bd7dd6c
web-1  | 03/25/2025 13:03:11 [Information] - CoverCalibrator 0 - Starting initialisation
web-1  | 03/25/2025 13:03:11 [Information] - CoverCalibrator 0 - UUID of 0e16f300-9fa4-40e4-9837-a9bf78ee8e14
web-1  | 03/25/2025 13:03:11 [Information] - CoverCalibrator 0 - Set calibrator timer to: 2000ms.
web-1  | 03/25/2025 13:03:11 [Information] - CoverCalibrator 0 - Set cover timer to: 5000ms.
web-1  | 03/25/2025 13:03:11 [Information] - CoverCalibrator 0 - Completed initialisation
web-1  | 03/25/2025 13:03:11 [Information] - Dome 0 - UUID of aaea7477-75ca-44d0-9c66-5652e2fd56f8
web-1  | 03/25/2025 13:03:11 [Information] - FilterWheel 0 - UUID of 21abcae7-885c-4b18-9c28-c0e6b9181cab
web-1  | 03/25/2025 13:03:11 [Information] - FilterWheel 0 - Starting initialization
web-1  | 03/25/2025 13:03:11 [Information] - Focuser 0 - UUID of 80e3fad2-1756-40f3-822a-74b3eca90684
web-1  | 03/25/2025 13:03:11 [Information] - ObservingConditions 0 - UUID of b61520f4-0811-451b-aea0-6aa9ea53a85d
web-1  | 03/25/2025 13:03:11 [Information] - Rotator 0 - UUID of 1e690b05-e71e-48b1-9519-b62d7c9ee299
web-1  | 03/25/2025 13:03:11 [Information] - SafetyMonitor 0 - UUID of e616e6c0-b3fe-4660-8782-79022640960f
web-1  | 03/25/2025 13:03:11 [Information] - Switch 0 - UUID of 2c08e6e0-aec6-4078-a651-a946d79abb64
web-1  | 03/25/2025 13:03:11 [Information] - TelescopeHardware: Alignment mode 1: AltAz
web-1  | 03/25/2025 13:03:11 [Information] - TelescopeHardware: Alignment mode 2: GermanPolar
web-1  | 03/25/2025 13:03:11 [Information] - TelescopeHardware: German Polar - Setting HomeAxes to 0 51.07861
web-1  | 03/25/2025 13:03:11 [Information] - TelescopeHardware New: Startup mode: Start up at simulator Default Position, Azimuth: 180, Altitude: 38.92139
web-1  | 03/25/2025 13:03:11 [Information] - TelescopeHardware New: Successfully initialised hardware
web-1  | 03/25/2025 13:03:11 [Information] - GetId: Generated new ID: 1
web-1  | 03/25/2025 13:03:11 [Information] - Telescope 0 - UUID of 65d49e5a-46d9-4bd7-a547-9f65ac3e5123
web-1  | 03/25/2025 13:03:11 [Information] - New: Instance ID: 1, new: Driver ID: Alpaca Simulator
web-1 exited with code 0
 onekiloparsec@hal9014  ~/code/ASCOM.Alpaca.Simulators  ➦ b9cf9c6 ● <B> 
```

**Comment by DanielVanNoord** [comment]
Do you mind giving it a try now? It should be fixed with a472045ed3139ce9b1934585b7e8b41565238f65

**Comment by onekiloparsec** [comment]
Wonderful, indeed it works now! Thank you very much. I close the issue, then.

P.S. I am still failing to use Alpyca's discovery methods though (even if I expose the port `32227`), but at least I can use the APIs/Swagger.

**Comment by DanielVanNoord** [comment]
@onekiloparsec I updated the docker-compose file on the develop1.0 branch so it should work with discovery (at least from the machine that hosts the docker container). Do you mind giving that a try as well?

**Comment by onekiloparsec** [comment]
Simply the [Alpyca](https://github.com/ASCOMInitiative/alpyca/) method: 


```
from alpaca import discovery
discovery.search_ipv4()
```

**Comment by DanielVanNoord** [comment]
Interesting, at least on my Ubuntu machine both this Alpyca code

```
from alpaca import discovery

svrs = discovery.search_ipv4()  # Note there is an IPv6 function as well
print(svrs)
```

and the Python and C example from [https://github.com/DanielVanNoord/AlpacaDiscoveryTests](https://github.com/DanielVanNoord/AlpacaDiscoveryTests) are working with the updated Docker file. I can't test on macOS right now but can later.

Note that discovery only works on the same machine that hosts the Docker container, but I was able to get it working across the network by setting the C discovery device code example to the Alpaca API Docker port and binding it to the host machine's ipv4 address.

**Comment by onekiloparsec** [comment]
Thanks for checking, I forgot about this test repo. 

I managed to make it work with the containers too, with a few teaks, by comparing the Python section of the AlpacaDiscoveryTests and the Alpyca one. 

I am not good enough at networking, but there are two differences between the python section in the AlpacaDiscoveryTests repo and the Alpyca code. 

First, [these lines](https://github.com/ASCOMInitiative/alpyca/blob/5b9d5c9a477da80334f7b6f9ff358220e5eeb5e9/alpaca/discovery.py#L96) not present in AlpacaDiscoveryTests:

```
    if(addr ==  '127.0.0.1'):
        sock.sendto(AlpacaDiscovery.encode(),
                    ('127.255.255.255', port))
    elif('broadcast' in ip):
        ...
```

In AlpacaDiscoveryTests there is only `if ('broadcast' in ip):`...

Then, [these ones](https://github.com/ASCOMInitiative/alpyca/blob/5b9d5c9a477da80334f7b6f9ff358220e5eeb5e9/alpaca/discovery.py#L109):

```
      if(remip == addr and remip != '127.0.0.1'):
          continue                # avoid router loop back to ourselves
```

Which basically filter out everything that is being discovered, in my case.

**Comment by onekiloparsec** [comment]
Not sure what to do next. :-)

**Comment by DanielVanNoord** [comment]
I'll take a look at the Alpyca code and have a chat with the maintainer. Thanks for letting me know about this.

**Comment by onekiloparsec** [comment]
Thanks a lot!

**Comment by onekiloparsec** [comment]
Hello @DanielVanNoord . Did you manage to talk with Alpyca maintainer?
